### ISSUE TITLE
algo.itcharge.cn 搭建疑惑

### ISSUE THREAD

**Issue by clay9** [itcharge/itcharge#1]
您好, 冒昧打扰, 请问您的站点algo.itcharge.cn 是用什么软件和主题搭建的. 谢谢

**Comment by itcharge** [comment]
> 您好, 冒昧打扰, 请问您的站点algo.itcharge.cn 是用什么软件和主题搭建的. 谢谢

使用的是 Vuepress，主题是 vuepress-theme-hope

**Comment by clay9** [comment]
感谢解惑

**Comment by itcharge** [comment]
> 感谢解惑

不客气哈～
